### ISSUE TITLE
Incorrect Steps Per MM

### ISSUE THREAD

**Issue by pomeroyb** [jellyfush/uncia-gcode#1]
As seen in this thread of the [Uncia Google Group](https://groups.google.com/forum/#!topic/uncia-3d-printer/33GWkmPRCzI), we discovered that the correct steps per mm for the Uncia is 87. Your steps per mm (Line 42) is 80.

It's an easy "aftermarket" fix, but it'd be nice for it to be correct in the source! :)

**Comment by jellyfush** [comment]
Thanks. Changed to 87
